// Buổi 4 · Chuyển giao đời sống: hai câu bối cảnh đời thường cho mỗi nhiệm vụ.
// Cùng ý tưởng toán của nhiệm vụ, nhưng câu chuyện khác hẳn câu luyện (chợ, bếp, xe buýt, tiết kiệm…).
// Cùng quy ước với bộ sinh đề (xem kit.ts): tầng 1 là câu hỏi, tầng 3 không nêu đáp án,
// mỗi đáp án sai hay gặp có phản hồi riêng. Hai bộ kiểm định chạy trên toàn bộ các câu này.

import { num, pick, type Q } from "./kit";

const TAG = "Đời sống";

export const LIFE_TRANSFER: Record<string, [Q, Q]> = {
  "number-1": [
    num("Mẹ nuôi heo đất: tuần 1 có 15 nghìn đồng, mỗi tuần bỏ thêm 6 nghìn đồng. Đến tuần 5, heo đất có bao nhiêu nghìn đồng?", 39,
      ["Từ tuần 1 đến tuần 5 có mấy lần bỏ thêm tiền?", "15 → 21 → 27 → … (mỗi tuần thêm 6)", "Có 4 lần bỏ thêm: tính 15 + 4 × 6."],
      "Từ tuần 1 đến tuần 5 có 4 lần bỏ thêm: 15 + 4 × 6 = 39 nghìn đồng.", TAG,
      { steps: 2, wrong: { 45: "Con đã cộng 5 lần. Từ tuần 1 đến tuần 5 chỉ có 4 lần bỏ thêm.", 21: "Đó mới là số tiền ở tuần 2. Con đi tiếp đến tuần 5 nhé." } }),
    pick("Xe buýt trường chạy lúc 6:40, 6:55, 7:10, 7:25. Chuyến tiếp theo chạy lúc mấy giờ?", "7:40", ["7:30", "7:35", "7:40", "8:25"],
      ["Hai chuyến liền nhau cách nhau bao nhiêu phút?", "Từ 6:40 đến 6:55 là 15 phút.", "Lấy 7:25 cộng thêm khoảng cách giữa hai chuyến."],
      "Mỗi chuyến cách nhau 15 phút. 7:25 thêm 15 phút là 7:40.", TAG,
      { wrong: { "7:30": "Con đã cộng 5 phút. Khoảng cách giữa hai chuyến là 15 phút.", "7:35": "Con đã cộng 10 phút. Hãy đo lại khoảng cách từ 6:40 đến 6:55.", "8:25": "Con đã cộng 1 giờ, nhưng các chuyến chỉ cách nhau 15 phút." } }),
  ],
  "number-2": [
    num("Bố đặt mật khẩu vali gồm ba chữ số 2, 5, 8, mỗi chữ số dùng đúng một lần. Có bao nhiêu cách đặt khác nhau?", 6,
      ["Nếu chữ số đầu là 2, còn mấy cách xếp hai chữ số sau?", "Đầu 2: 258, 285. Đầu 5: …", "Mỗi chữ số đứng đầu có 2 cách; có 3 chữ số có thể đứng đầu."],
      "Mỗi chữ số đứng đầu có 2 cách xếp phần còn lại: 3 × 2 = 6 cách.", TAG,
      { steps: 2, wrong: { 3: "Con mới đếm mỗi chữ số đứng đầu một lần. Mỗi trường hợp còn 2 cách xếp.", 9: "Mỗi chữ số chỉ dùng một lần, nên không có 225 hay 588." } }),
    num("Lan có ba thẻ số 3, 0, 7. Lan ghép số có ba chữ số nhỏ nhất, mỗi thẻ dùng một lần. Đó là số nào?", 307,
      ["Chữ số 0 có được đứng ở hàng trăm không?", "Hàng trăm: chọn thẻ nhỏ nhất nhưng khác 0.", "Đặt 3 ở hàng trăm, rồi xếp hai thẻ còn lại từ nhỏ đến lớn."],
      "Số 0 không đứng đầu được, nên hàng trăm là 3; tiếp theo là 0 rồi 7: số 307.", TAG,
      { steps: 2, wrong: { 37: "Số 037 thật ra chỉ có hai chữ số. Hàng trăm không được là 0.", 370: "370 lớn hơn 307. Sau hàng trăm, đặt thẻ nhỏ hơn trước.", 703: "Đó là một số lớn. Con cần số nhỏ nhất." } }),
  ],
  "number-3": [
    pick("Lớp có 27 bạn. Cô muốn xếp cả lớp thành từng đôi, không ai bị lẻ. Cô làm được không?", "Không", ["Có", "Không"],
      ["27 là số chẵn hay số lẻ?", "Xếp đôi vừa hết khi số người là số chẵn.", "Xét chữ số hàng đơn vị của 27."],
      "27 là số lẻ nên xếp đôi xong vẫn thừa 1 bạn.", TAG,
      { wrong: { "Có": "Thử xếp: 13 đôi mới có 26 bạn, vẫn còn 1 bạn chưa có đôi." } }),
    pick("Minh mua 3 món, giá mỗi món là một số lẻ nghìn đồng. Tổng số tiền là số chẵn hay số lẻ?", "Số lẻ", ["Số chẵn", "Số lẻ", "Chưa biết được"],
      ["Số lẻ cộng số lẻ được số chẵn hay số lẻ?", "Lẻ cộng lẻ được chẵn; chẵn cộng lẻ thì sao?", "Cộng giá hai món đầu trước, rồi cộng món thứ ba."],
      "Hai số lẻ cộng lại được số chẵn; số chẵn cộng thêm một số lẻ được số lẻ.", TAG,
      { steps: 2, wrong: { "Số chẵn": "Hai món đầu cho số chẵn, nhưng còn món thứ ba có giá lẻ.", "Chưa biết được": "Không cần biết giá cụ thể: chỉ cần biết mỗi giá là số lẻ." } }),
  ],
  "number-4": [
    num("Hà đo cây đậu mỗi tuần: 4 cm, 7 cm, 10 cm, 14 cm, 16 cm. Cây lớn đều nhưng Hà ghi nhầm một số. Số đúng phải là bao nhiêu?", 13,
      ["Ba tuần đầu, mỗi tuần cây cao thêm bao nhiêu?", "4 → 7 → 10: mỗi tuần thêm 3 cm.", "Từ 10 cộng thêm 3, rồi so với số Hà đã ghi."],
      "Cây cao đều thêm 3 cm mỗi tuần: 4, 7, 10, 13, 16. Số 14 bị ghi nhầm, đúng phải là 13.", TAG,
      { steps: 2, wrong: { 14: "14 chính là số bị ghi nhầm. Con hãy tìm số đúng thay cho nó.", 17: "Con đã cộng 3 vào 14. Hãy cộng vào số đúng trước đó là 10." } }),
    num("Ông tưới cây vào ngày 2, ngày 5, ngày 8, ngày 11 trong tháng và giữ đúng quy luật ấy. Lần tưới thứ bảy vào ngày nào?", 20,
      ["Hai lần tưới liền nhau cách nhau mấy ngày?", "2 → 5 → 8 → 11 → … (mỗi lần thêm 3)", "Từ lần 1 đến lần 7 có 6 khoảng: tính 2 + 6 × 3."],
      "Mỗi lần cách 3 ngày. Từ lần 1 đến lần 7 có 6 khoảng: 2 + 6 × 3 = 20.", TAG,
      { steps: 2, wrong: { 23: "Con đã tính 7 khoảng. Từ lần 1 đến lần 7 chỉ có 6 khoảng.", 14: "Ngày 14 là lần tưới thứ năm. Con đi thêm hai lần nữa." } }),
  ],
  "number-5": [
    pick("Bà uống thuốc cứ 8 giờ một lần. Lần đầu lúc 7 giờ sáng. Lần thứ ba bà uống lúc mấy giờ?", "11 giờ đêm", ["3 giờ chiều", "9 giờ tối", "11 giờ đêm", "7 giờ sáng hôm sau"],
      ["Từ lần thứ nhất đến lần thứ ba có mấy khoảng 8 giờ?", "7 giờ sáng → 3 giờ chiều → …", "Cộng thêm 8 giờ hai lần; nhớ rằng qua 12 giờ trưa thì đếm lại từ 1."],
      "Lần hai: 7 giờ sáng thêm 8 giờ là 3 giờ chiều. Lần ba: 3 giờ chiều thêm 8 giờ là 11 giờ đêm.", TAG,
      { steps: 2, wrong: { "3 giờ chiều": "Đó là lần thứ hai. Con thêm 8 giờ nữa nhé.", "9 giờ tối": "Con đã thêm 6 giờ ở lần sau. Mỗi lần cách nhau đúng 8 giờ.", "7 giờ sáng hôm sau": "Con đã đi 3 khoảng 8 giờ. Từ lần một đến lần ba chỉ có 2 khoảng." } }),
    num("Đèn trang trí nháy theo vòng: đỏ, vàng, xanh, tím, rồi lặp lại. Lần nháy đầu là đỏ. Trong 18 lần nháy đầu, đèn đỏ sáng mấy lần?", 5,
      ["Đèn đỏ sáng ở những lần thứ mấy?", "Đỏ ở lần 1, lần 5, lần 9, … (cứ 4 lần lại đến đỏ)", "Viết tiếp dãy 1, 5, 9 cho đến khi vượt quá 18, rồi đếm."],
      "Đèn đỏ sáng ở lần 1, 5, 9, 13, 17: tất cả 5 lần.", TAG,
      { steps: 2, wrong: { 4: "Con quên lần nháy đầu tiên: lần 1 cũng là đỏ.", 18: "18 là số lần nháy của mọi màu, không chỉ màu đỏ." } }),
  ],
  "number-6": [
    num("Nam xếp ghế xem văn nghệ: hàng 1 có 6 ghế, mỗi hàng sau nhiều hơn hàng trước 2 ghế. Hàng thứ năm có bao nhiêu ghế?", 14,
      ["Từ hàng 1 đến hàng 5, số ghế tăng thêm mấy lần?", "6 → 8 → 10 → …", "Có 4 lần tăng, mỗi lần 2 ghế: tính 6 + 4 × 2."],
      "Các hàng có 6, 8, 10, 12, 14 ghế: hàng thứ năm có 14 ghế.", TAG,
      { steps: 2, wrong: { 16: "Con đã tăng 5 lần. Từ hàng 1 đến hàng 5 chỉ có 4 lần tăng.", 12: "12 là số ghế ở hàng thứ tư. Con thêm một hàng nữa." } }),
    pick("Chị Mai đặt luật: “Bắt đầu từ 3, mỗi bước gấp đôi.” Em viết 3, 6, 9, 12. Em đã sai ở đâu?", "Em cộng 3 thay vì gấp đôi", ["Em cộng 3 thay vì gấp đôi", "Em bắt đầu sai số", "Em làm đúng luật"],
      ["Gấp đôi 6 thì được bao nhiêu?", "3 → 6 → 12 → …", "So từng bước em viết với luật “gấp đôi”."],
      "Gấp đôi mỗi bước cho 3, 6, 12, 24. Em đã cộng 3 mỗi bước nên viết 9 sau 6.", TAG,
      { wrong: { "Em bắt đầu sai số": "Em bắt đầu đúng từ 3. Lỗi nằm ở bước sau số 6.", "Em làm đúng luật": "Gấp đôi 6 được 12, không phải 9." } }),
  ],
  "calculation-1": [
    num("Mẹ mua áo giá 198 nghìn đồng và mũ giá 45 nghìn đồng. Tính nhẩm: tổng cộng bao nhiêu nghìn đồng?", 243,
      ["198 gần số tròn trăm nào?", "198 + 45 = 200 + □", "Chuyển 2 từ 45 sang 198, rồi cộng."],
      "198 + 45 = 200 + 43 = 243 nghìn đồng.", TAG,
      { steps: 2, wrong: { 245: "Con đã thêm 2 vào 198 mà quên bớt 2 ở 45.", 233: "Con xem lại phép cộng hàng chục: 200 + 43." } }),
    num("Bể có 604 lít nước. Bố dùng 298 lít để tưới vườn. Bể còn bao nhiêu lít nước?", 306,
      ["298 gần số tròn trăm nào?", "604 − 298 = 606 − 300", "Cộng 2 vào cả hai số, rồi trừ."],
      "604 − 298 = 606 − 300 = 306 lít.", TAG,
      { steps: 2, wrong: { 304: "Con đã thay 298 bằng 300 mà chưa bù lại 2.", 302: "Con đã bù ngược chiều. Trừ 300 là trừ thừa 2, nên phải cộng lại 2." } }),
  ],
  "calculation-2": [
    num("Một hộp bánh có 25 chiếc. Cô mua 8 hộp cho lớp. Có tất cả bao nhiêu chiếc bánh?", 200,
      ["25 có thể tách thành số tròn chục và số nào?", "25 × 8 = 20 × 8 + 5 × 8", "Tính từng phần rồi cộng lại."],
      "25 × 8 = 20 × 8 + 5 × 8 = 160 + 40 = 200 chiếc.", TAG,
      { steps: 2, wrong: { 165: "Con quên nhân 5 với 8: 160 + 5 chưa đủ.", 33: "Con đã cộng 25 + 8. Có 8 hộp, mỗi hộp 25 chiếc nên phải nhân." } }),
    num("Vé vào khu vui chơi giá 19 nghìn đồng. Nhà Bin có 6 người. Cả nhà phải trả bao nhiêu nghìn đồng?", 114,
      ["19 gần số tròn chục nào?", "19 × 6 = 20 × 6 − 1 × 6", "Tính 20 × 6 rồi bớt đi 6."],
      "19 × 6 = 20 × 6 − 6 = 120 − 6 = 114 nghìn đồng.", TAG,
      { steps: 2, wrong: { 120: "Con tính như vé giá 20 nghìn. Mỗi vé rẻ hơn 1 nghìn nên phải bớt 6.", 119: "Con chỉ bớt 1. Có 6 vé, mỗi vé rẻ hơn 1 nghìn." } }),
  ],
  "calculation-3": [
    num("Bình có một số con tem. Bình mua thêm 3 tập, mỗi tập 5 con tem, thì có tất cả 41 con tem. Lúc đầu Bình có bao nhiêu con tem?", 26,
      ["Bình đã mua thêm tất cả bao nhiêu con tem?", "□ + 3 × 5 = 41", "Tính số tem mua thêm, rồi lấy 41 trừ đi."],
      "Mua thêm 3 × 5 = 15 con tem. Lúc đầu: 41 − 15 = 26 con tem.", TAG,
      { steps: 2, wrong: { 38: "Con mới trừ 3 tập, chưa đổi ra số con tem: mỗi tập có 5 con.", 56: "Con đã cộng thêm. 41 là số tem sau khi mua, nên phải đi ngược bằng phép trừ." } }),
    num("Mẹ mua 4 hộp sữa cùng giá và một gói bánh giá 6 nghìn đồng, hết 46 nghìn đồng. Mỗi hộp sữa giá bao nhiêu nghìn đồng?", 10,
      ["Tiền mua 4 hộp sữa là bao nhiêu?", "4 × □ + 6 = 46", "Bớt tiền bánh trước, rồi chia đều cho 4 hộp."],
      "Tiền sữa: 46 − 6 = 40 nghìn. Mỗi hộp: 40 : 4 = 10 nghìn đồng.", TAG,
      { steps: 2, wrong: { 40: "40 nghìn là tiền của cả 4 hộp sữa. Con chia đều cho 4 hộp nhé.", 52: "Con đã cộng thêm tiền bánh. Phải bớt tiền bánh ra trước." } }),
  ],
  "calculation-4": [
    num("Giỏ A có 397 quả cam, giỏ B có 86 quả. Bác chuyển cam từ giỏ B sang để giỏ A tròn 400 quả. Giỏ B còn bao nhiêu quả?", 83,
      ["Giỏ A cần thêm mấy quả để tròn 400?", "397 + 86 = 400 + □", "Lấy 86 bớt đi số quả đã chuyển sang giỏ A."],
      "Giỏ A cần thêm 3 quả. Giỏ B còn 86 − 3 = 83 quả. Tổng vẫn là 400 + 83 = 483 quả.", TAG,
      { steps: 2, wrong: { 89: "Con đã thêm 3 vào giỏ B. Cam được chuyển đi nên giỏ B phải ít đi.", 3: "3 là số quả được chuyển. Câu hỏi là số cam còn lại trong giỏ B." } }),
    pick("Năm nay anh 13 tuổi, em 7 tuổi. Sau 5 năm nữa, anh hơn em bao nhiêu tuổi?", "6 tuổi", ["6 tuổi", "11 tuổi", "1 tuổi"],
      ["Sau 5 năm, mỗi người thêm mấy tuổi?", "(13 + 5) − (7 + 5)", "Hai số cùng tăng như nhau thì hiệu thay đổi thế nào?"],
      "Cả hai cùng thêm 5 tuổi nên hiệu giữ nguyên: 13 − 7 = 6 tuổi.", TAG,
      { steps: 2, wrong: { "11 tuổi": "Con chỉ cộng 5 cho anh. Em cũng lớn thêm 5 tuổi.", "1 tuổi": "Con chỉ cộng 5 cho em. Anh cũng lớn thêm 5 tuổi." } }),
  ],
  "calculation-5": [
    pick("Mẹ có 500 nghìn đồng, định mua nồi giá 289 nghìn và chảo giá 198 nghìn. Ước lượng nhanh: mẹ có đủ tiền không?", "Đủ", ["Đủ", "Không đủ"],
      ["289 và 198 gần số tròn trăm nào?", "289 gần 300, còn 198 gần 200.", "Mỗi giá đều nhỏ hơn số tròn trăm của nó; so tổng ước lượng với 500."],
      "289 nhỏ hơn 300 và 198 nhỏ hơn 200, nên tổng nhỏ hơn 500. Tổng thật là 487 nghìn đồng.", TAG,
      { steps: 2, wrong: { "Không đủ": "Làm tròn lên: 300 + 200 = 500. Hai giá thật còn nhỏ hơn hai số tròn đó." } }),
    pick("Bạn Tí tính tiền 4 cuốn truyện, mỗi cuốn 48 nghìn đồng, ra 132 nghìn đồng. Kết quả này có hợp lý không?", "Không", ["Có", "Không"],
      ["48 gần số tròn chục nào?", "48 gần 50; 50 × 4 = 200", "So kết quả của Tí với ước lượng 50 × 4."],
      "48 × 4 phải gần 200, nên 132 là vô lý. Kết quả đúng là 192 nghìn đồng.", TAG,
      { wrong: { "Có": "Ước lượng: 50 × 4 = 200. Con số 132 kém xa 200 nên đáng nghi." } }),
  ],
  "calculation-6": [
    num("Lan cần trả đúng 35 nghìn đồng. Lan đã đưa 2 tờ 10 nghìn. Lan cần đưa thêm mấy tờ 5 nghìn?", 3,
      ["Hai tờ 10 nghìn là bao nhiêu tiền?", "2 × 10 + □ × 5 = 35", "Bớt phần đã trả, rồi chia phần còn thiếu cho 5."],
      "2 × 10 = 20. Còn thiếu 35 − 20 = 15 nghìn, tức 15 : 5 = 3 tờ 5 nghìn.", TAG,
      { steps: 2, wrong: { 15: "15 nghìn là số tiền còn thiếu. Mỗi tờ 5 nghìn, nên chia tiếp cho 5.", 7: "Con đã trả cả 35 nghìn bằng tờ 5 nghìn. Lan đã đưa 2 tờ 10 nghìn rồi." } }),
    pick("Hằng muốn xếp đúng 24 chiếc bánh vào các khay, khay nào cũng như nhau. Cách xếp nào KHÔNG cho đúng 24 chiếc?", "5 khay, mỗi khay 5 chiếc", ["3 khay, mỗi khay 8 chiếc", "4 khay, mỗi khay 6 chiếc", "5 khay, mỗi khay 5 chiếc", "2 khay, mỗi khay 12 chiếc"],
      ["Mỗi cách xếp cho bao nhiêu chiếc bánh?", "Tính từng tích: 3 × 8, 4 × 6, …", "Tìm cách xếp có tích khác 24."],
      "3 × 8, 4 × 6 và 2 × 12 đều cho 24 chiếc. Còn 5 × 5 = 25 chiếc.", TAG,
      { wrong: { "3 khay, mỗi khay 8 chiếc": "3 × 8 = 24: cách này đúng 24 chiếc.", "4 khay, mỗi khay 6 chiếc": "4 × 6 = 24: cách này đúng 24 chiếc.", "2 khay, mỗi khay 12 chiếc": "2 × 12 = 24: cách này đúng 24 chiếc." } }),
  ],
  "measurement-1": [
    pick("Bố muốn đo chiều dài phòng khách nhà mình. Kết quả nào hợp lý nhất?", "Khoảng 5 m", ["Khoảng 5 cm", "Khoảng 5 m", "Khoảng 5 km"],
      ["Một bước chân người lớn dài khoảng bao nhiêu?", "Một bước chân người lớn gần 1 m.", "Tưởng tượng phòng dài mấy bước chân, rồi chọn đơn vị."],
      "Phòng khách dài vài bước chân, mỗi bước gần 1 m, nên khoảng 5 m là hợp lý.", TAG,
      { wrong: { "Khoảng 5 cm": "5 cm chỉ dài bằng một ngón tay.", "Khoảng 5 km": "5 km là quãng đường đi bộ mất cả tiếng đồng hồ." } }),
    num("Cuộn ruy băng dài 3 m. Mẹ cắt đi 75 cm để gói quà. Phần còn lại dài bao nhiêu xăng-ti-mét?", 225,
      ["3 m bằng bao nhiêu xăng-ti-mét?", "3 m = 300 cm", "Đổi ra xăng-ti-mét, rồi trừ phần đã cắt."],
      "3 m = 300 cm; 300 − 75 = 225 cm.", TAG,
      { steps: 2, wrong: { 72: "Con lấy 75 − 3 mà chưa đổi 3 m ra xăng-ti-mét.", 235: "Con xem lại phép trừ có nhớ: 300 − 75." } }),
  ],
  "measurement-2": [
    num("Bố có 36 m lưới để rào vườn rau hình chữ nhật dài 11 m. Vườn rộng bao nhiêu mét?", 7,
      ["Nửa chu vi của vườn là bao nhiêu mét?", "36 : 2 = 18; 18 = 11 + □", "Lấy nửa chu vi trừ chiều dài."],
      "Nửa chu vi: 36 : 2 = 18 m. Chiều rộng: 18 − 11 = 7 m.", TAG,
      { steps: 2, wrong: { 25: "Con lấy 36 − 11. Lưới rào bao cả bốn cạnh: hai cạnh dài và hai cạnh rộng.", 14: "14 m là tổng hai cạnh rộng. Mỗi cạnh rộng chỉ bằng một nửa." } }),
    num("Nhà Mai có 200 nghìn đồng để đi chơi. Vé xe hết 64 nghìn, tiền ăn hết 85 nghìn. Còn lại bao nhiêu nghìn đồng?", 51,
      ["Hai khoản đã tiêu tổng cộng bao nhiêu?", "64 + 85 = □; rồi 200 − □", "Cộng hai khoản chi, rồi lấy 200 trừ đi."],
      "Đã tiêu 64 + 85 = 149 nghìn. Còn 200 − 149 = 51 nghìn đồng.", TAG,
      { steps: 2, wrong: { 136: "Con mới trừ tiền vé xe. Còn tiền ăn nữa.", 115: "Con mới trừ tiền ăn. Còn tiền vé xe nữa." } }),
  ],
  "measurement-3": [
    pick("Ông có 16 m lưới rào một vườn rau hình chữ nhật, các cạnh là số mét tròn. Vườn nào trồng được nhiều rau nhất?", "4 m × 4 m", ["1 m × 7 m", "2 m × 6 m", "3 m × 5 m", "4 m × 4 m"],
      ["Mỗi vườn có diện tích bao nhiêu mét vuông?", "Nửa chu vi là 8 m: 1 và 7, 2 và 6, 3 và 5, 4 và 4.", "Tính diện tích từng vườn rồi so sánh."],
      "Diện tích lần lượt là 7, 12, 15 và 16 m². Vườn có hai cạnh bằng nhau rộng nhất.", TAG,
      { steps: 2, wrong: { "1 m × 7 m": "Vườn 1 m × 7 m chỉ rộng 7 m², hẹp nhất.", "2 m × 6 m": "Vườn 2 m × 6 m rộng 12 m², chưa phải lớn nhất.", "3 m × 5 m": "Vườn 3 m × 5 m rộng 15 m², vẫn kém vườn có hai cạnh bằng nhau." } }),
    num("Bác Tư dùng 20 m lưới rào chuồng gà hình chữ nhật dài 6 m. Diện tích chuồng là bao nhiêu mét vuông?", 24,
      ["Chiều rộng chuồng là bao nhiêu mét?", "Nửa chu vi: 20 : 2 = 10 m; chiều rộng: 10 − 6", "Tìm chiều rộng rồi nhân với chiều dài."],
      "Nửa chu vi 10 m, chiều rộng 10 − 6 = 4 m. Diện tích 6 × 4 = 24 m².", TAG,
      { steps: 3, wrong: { 84: "Con lấy 20 − 6 = 14 làm chiều rộng. Hãy lấy nửa chu vi trừ chiều dài.", 20: "20 m là chu vi. Câu hỏi là diện tích chuồng.", 10: "10 m là nửa chu vi, chưa phải diện tích." } }),
  ],
  "measurement-4": [
    num("Trên bản đồ khu phố, mỗi ô vuông ứng với 50 m. Từ nhà Minh đến trường dài 6 ô. Quãng đường thật dài bao nhiêu mét?", 300,
      ["Mỗi ô ứng với bao nhiêu mét ngoài đời?", "6 ô: 6 × 50 m", "Nhân số ô với số mét của mỗi ô."],
      "6 × 50 = 300 m.", TAG,
      { wrong: { 56: "Con đã cộng 6 + 50. Có 6 ô, mỗi ô 50 m nên phải nhân.", 250: "Con đếm thiếu một ô: 5 × 50 mới là 5 ô." } }),
    num("Bản đồ công viên ghi: 1 cm trên bản đồ ứng với 100 m ngoài đời. Đường chạy đo được 8 cm. Lan chạy hết đường đó rồi quay về. Lan chạy bao nhiêu mét?", 1600,
      ["Đường chạy thật dài bao nhiêu mét?", "8 cm ứng với 8 × 100 m", "Tìm chiều dài thật, rồi nhân đôi vì đi và về."],
      "Đường thật dài 8 × 100 = 800 m. Đi và về: 800 × 2 = 1600 m.", TAG,
      { steps: 2, wrong: { 800: "800 m mới là chiều đi. Lan còn chạy quay về.", 16: "Con mới nhân đôi số xăng-ti-mét. Mỗi xăng-ti-mét ứng với 100 m." } }),
  ],
  "measurement-5": [
    pick("Lớp học bơi bắt đầu lúc 15:30 và kéo dài 45 phút. Đi bộ từ bể bơi về nhà mất 20 phút. Bin về đến nhà lúc mấy giờ?", "16:35", ["16:15", "16:35", "16:05", "17:15"],
      ["Từ 15:30, Bin mất tất cả bao nhiêu phút?", "45 + 20 = 65 phút, tức 1 giờ 5 phút", "Cộng 1 giờ vào 15:30, rồi thêm 5 phút."],
      "Bơi xong lúc 16:15, thêm 20 phút đi bộ: Bin về đến nhà lúc 16:35.", TAG,
      { steps: 2, wrong: { "16:15": "Đó là lúc bơi xong. Bin còn đi bộ 20 phút nữa.", "16:05": "Con mới cộng 35 phút. Tổng thời gian là 65 phút.", "17:15": "Con đã cộng 1 giờ 45 phút. Hãy cộng 45 phút và 20 phút trước." } }),
    num("Buổi chiều Hằng có 2 giờ. Hằng làm bài tập 50 phút, giúp mẹ nấu cơm 40 phút. Hằng còn bao nhiêu phút để chơi?", 30,
      ["2 giờ bằng bao nhiêu phút?", "2 giờ là 120 phút; đã dùng 50 + 40 phút", "Tính tổng thời gian đã dùng, rồi lấy 120 trừ đi."],
      "2 giờ là 120 phút. Đã dùng 50 + 40 = 90 phút. Còn 120 − 90 = 30 phút.", TAG,
      { steps: 3, wrong: { 90: "90 phút là thời gian Hằng đã dùng. Câu hỏi là thời gian còn lại.", 70: "Con mới trừ thời gian làm bài tập. Còn thời gian nấu cơm nữa." } }),
  ],
  "measurement-6": [
    num("Lớp có 100 nghìn đồng mua bút màu. Mỗi hộp giá 18 nghìn đồng. Lớp mua được nhiều nhất mấy hộp?", 5,
      ["Mỗi lần mua thêm một hộp, tổng tiền tăng bao nhiêu?", "18, 36, 54, 72, …", "Cộng dần 18 cho đến khi sắp vượt 100 nghìn, rồi đếm số hộp."],
      "18 × 5 = 90 nghìn (đủ tiền), 18 × 6 = 108 nghìn (thiếu tiền). Mua được nhiều nhất 5 hộp.", TAG,
      { steps: 2, wrong: { 6: "6 hộp giá 108 nghìn, vượt quá 100 nghìn.", 10: "Con đã chia 100 cho 10. Mỗi hộp giá 18 nghìn." } }),
    num("Cần ít nhất 26 quả bóng bay cho buổi tiệc. Mỗi túi có 8 quả. Phải mua ít nhất mấy túi?", 4,
      ["3 túi có đủ 26 quả không?", "8, 16, 24, 32, …", "Tìm số túi đầu tiên có từ 26 quả trở lên."],
      "3 túi có 24 quả, chưa đủ. 4 túi có 32 quả, đủ dùng.", TAG,
      { steps: 2, wrong: { 3: "3 túi chỉ có 24 quả, còn thiếu 2 quả.", 32: "32 là số quả bóng, không phải số túi." } }),
  ],
  "geometry-1": [
    num("Bố lát sàn ban công hình chữ nhật bằng 24 viên gạch vuông cạnh 1 dm, xếp thành 4 hàng. Nẹp viền quanh sàn dài bao nhiêu đề-xi-mét?", 20,
      ["Mỗi hàng có bao nhiêu viên gạch?", "24 viên xếp 4 hàng: mỗi hàng 24 : 4 viên", "Tìm cạnh còn lại, rồi tính (dài + rộng) × 2."],
      "Mỗi hàng 24 : 4 = 6 viên. Sàn 4 × 6, nẹp viền dài (4 + 6) × 2 = 20 dm.", TAG,
      { steps: 3, wrong: { 24: "24 là diện tích (số viên gạch), không phải đường viền.", 10: "Con mới cộng 4 + 6. Nẹp viền chạy quanh cả bốn cạnh." } }),
    pick("Hai tấm thảm cùng phủ 36 ô vuông: tấm A là 4 × 9, tấm B là 6 × 6. Mẹ may ren quanh mép. Tấm nào cần ít ren hơn?", "Tấm B", ["Tấm A", "Tấm B", "Như nhau"],
      ["Chu vi mỗi tấm là bao nhiêu?", "Tấm A: (4 + 9) × 2; tấm B: (6 + 6) × 2", "Tính hai chu vi rồi so sánh."],
      "Tấm A cần (4 + 9) × 2 = 26, tấm B cần (6 + 6) × 2 = 24. Tấm B gọn hơn nên cần ít ren hơn.", TAG,
      { steps: 2, wrong: { "Tấm A": "Tấm A dài và hẹp, mép bao quanh dài 26, nhiều hơn tấm kia.", "Như nhau": "Cùng diện tích chưa chắc cùng chu vi: 26 và 24 khác nhau." } }),
  ],
  "geometry-2": [
    num("Mẹ cắt tấm bánh hình chữ nhật 6 × 4 ô thành hai phần. Một phần có 10 ô. Phần còn lại có bao nhiêu ô?", 14,
      ["Cả tấm bánh có bao nhiêu ô?", "6 × 4 = □; rồi □ − 10", "Tìm diện tích cả tấm, rồi bớt phần đã biết."],
      "Cả tấm 6 × 4 = 24 ô. Phần còn lại 24 − 10 = 14 ô.", TAG,
      { steps: 2, wrong: { 10: "Hai phần không nhất thiết bằng nhau. Hãy tính cả tấm trước.", 20: "Con đã lấy 6 + 4 + 10. Diện tích tấm bánh là 6 × 4 ô." } }),
    pick("Bé cắt tờ giấy hình vuông thành 4 mảnh rồi xếp thành hình con mèo, không chồng, không bỏ mảnh nào. So với tờ giấy lúc đầu, hình con mèo thế nào?", "Diện tích bằng nhau", ["Diện tích bằng nhau", "Diện tích lớn hơn", "Diện tích nhỏ hơn"],
      ["Có mảnh giấy nào bị thêm vào hay bỏ đi không?", "Hình con mèo gồm đúng 4 mảnh của tờ giấy cũ.", "Cắt rồi ghép đủ các mảnh, không chồng lên nhau: phần giấy có đổi không?"],
      "Vẫn là 4 mảnh ấy, không chồng, không bỏ, nên diện tích giữ nguyên. Chỉ hình dạng và chu vi có thể đổi.", TAG,
      { wrong: { "Diện tích lớn hơn": "Hình con mèo trông to hơn, nhưng vẫn chỉ là 4 mảnh giấy cũ.", "Diện tích nhỏ hơn": "Không mảnh nào bị bỏ đi, nên phần giấy không ít đi." } }),
  ],
  "geometry-3": [
    num("Thanh sô-cô-la có 5 ô xếp thành một hàng. Bẻ theo các rãnh, có bao nhiêu cách lấy ra một miếng gồm các ô liền nhau?", 15,
      ["Có bao nhiêu miếng chỉ gồm 1 ô? Bao nhiêu miếng gồm 2 ô?", "1 ô: 5 miếng; 2 ô: 4 miếng; 3 ô: …", "Đếm theo cỡ từ 1 ô đến 5 ô, rồi cộng lại."],
      "5 + 4 + 3 + 2 + 1 = 15 cách.", TAG,
      { steps: 2, wrong: { 5: "Con mới đếm miếng 1 ô. Còn các miếng gồm 2, 3, 4 và 5 ô.", 14: "Con quên miếng lớn nhất: cả thanh 5 ô." } }),
    num("Khung cửa sổ chia thành lưới 2 × 2 ô kính. Có tất cả bao nhiêu hình vuông?", 5,
      ["Ngoài 4 ô nhỏ, còn hình vuông nào lớn hơn không?", "4 hình vuông nhỏ, và một hình vuông bao quanh cả lưới.", "Đếm hình vuông 1 ô, rồi đếm hình vuông 2 × 2."],
      "4 hình vuông nhỏ và 1 hình vuông lớn: 5 hình vuông.", TAG,
      { steps: 2, wrong: { 4: "Con quên hình vuông lớn bao quanh cả 4 ô.", 9: "9 là số hình chữ nhật. Câu hỏi chỉ đếm hình vuông." } }),
  ],
  "geometry-4": [
    num("Chị Lan gấp đôi tờ giấy rồi cắt 3 lỗ xuyên qua hai lớp, không lỗ nào nằm trên nếp gấp. Mở ra, tờ giấy có bao nhiêu lỗ?", 6,
      ["Mỗi lần cắt xuyên qua mấy lớp giấy?", "Cắt 1 lỗ thì khi mở ra thấy 2 lỗ.", "Mỗi lỗ cắt tạo một lỗ ở mỗi lớp: nhân số lỗ cắt với số lớp."],
      "Mỗi lỗ cắt xuyên 2 lớp nên thành 2 lỗ. 3 × 2 = 6 lỗ.", TAG,
      { steps: 2, wrong: { 3: "Con quên lớp giấy bên dưới. Mỗi lỗ cắt xuyên qua 2 lớp.", 5: "Mỗi lỗ cắt cho đúng 2 lỗ khi mở ra. Con đếm lại nhé." } }),
    pick("Bé muốn gấp đôi tấm thiệp hình chữ nhật (không phải hình vuông) sao cho hai nửa trùng khít. Có mấy cách gấp như vậy?", "2 cách", ["1 cách", "2 cách", "4 cách"],
      ["Gấp theo đường chéo thì hai nửa có trùng khít không?", "Thử gấp dọc, gấp ngang, gấp chéo.", "Đếm những đường gấp làm hai nửa trùng khít."],
      "Hình chữ nhật không vuông có 2 trục đối xứng: gấp dọc chính giữa và gấp ngang chính giữa. Gấp chéo thì hai nửa không trùng.", TAG,
      { wrong: { "1 cách": "Ngoài gấp dọc, gấp ngang chính giữa cũng trùng khít.", "4 cách": "4 trục là của hình vuông. Tấm thiệp không vuông gấp chéo thì không trùng." } }),
  ],
  "geometry-5": [
    num("Nền bếp hình chữ nhật gồm 8 × 6 ô vuông. Bố lát bằng gạch to 2 × 2 ô. Cần bao nhiêu viên gạch?", 12,
      ["Mỗi viên gạch phủ bao nhiêu ô?", "Nền có 8 × 6 ô; mỗi viên phủ 2 × 2 ô", "Đếm số viên theo chiều dài và theo chiều rộng, rồi nhân."],
      "Mỗi hàng đặt 8 : 2 = 4 viên, có 6 : 2 = 3 hàng: 4 × 3 = 12 viên.", TAG,
      { steps: 2, wrong: { 48: "48 là số ô vuông nhỏ. Mỗi viên gạch phủ 4 ô.", 24: "Con chia 48 cho 2. Mỗi viên 2 × 2 phủ 4 ô, không phải 2 ô." } }),
    pick("Có thể lát kín hành lang 1 × 10 ô bằng gạch 1 × 3 ô, không cắt gạch được không?", "Không", ["Có", "Không"],
      ["10 ô có chia thành các nhóm 3 ô vừa hết không?", "3, 6, 9, 12, …", "Xem 10 có nằm trong dãy đếm thêm 3 không."],
      "3 viên phủ 9 ô, còn thừa 1 ô; 4 viên lại cần 12 ô. Không lát kín được.", TAG,
      { wrong: { "Có": "Thử xếp: 3 viên phủ 9 ô, còn 1 ô trống mà viên gạch dài 3 ô." } }),
  ],
  "geometry-6": [
    pick("Bác thợ lát sân hình chữ nhật bằng 36 viên gạch vuông, cạnh là số viên tròn. Muốn hàng rào quanh sân ngắn nhất, nên chọn sân nào?", "6 × 6", ["4 × 9", "3 × 12", "6 × 6", "2 × 18"],
      ["Chu vi mỗi sân là bao nhiêu?", "(4 + 9) × 2, (3 + 12) × 2, …", "Tính chu vi từng sân, rồi tìm chu vi nhỏ nhất."],
      "Chu vi: sân 4 × 9 là 26, sân 3 × 12 là 30, sân 6 × 6 là 24, sân 2 × 18 là 40. Sân có hai cạnh bằng nhau gọn nhất.", TAG,
      { steps: 2, wrong: { "4 × 9": "Sân 4 × 9 có chu vi 26, dài hơn sân có hai cạnh bằng nhau.", "3 × 12": "Sân 3 × 12 có chu vi 30, chưa phải ngắn nhất.", "2 × 18": "Sân 2 × 18 dài và hẹp, chu vi tới 40." } }),
    num("Nhà Nam làm chuồng thỏ hình chữ nhật có diện tích 12 m², cạnh là số mét tròn, dùng ít lưới rào nhất. Cần bao nhiêu mét lưới?", 14,
      ["Có những cặp cạnh nào cho diện tích 12 m²?", "1 × 12, 2 × 6, 3 × 4", "Tính chu vi từng cặp, rồi chọn số nhỏ nhất."],
      "Chu vi: chuồng 1 × 12 là 26 m, chuồng 2 × 6 là 16 m, chuồng 3 × 4 là 14 m. Ít lưới nhất là 14 m.", TAG,
      { steps: 3, wrong: { 16: "16 m là chu vi chuồng 2 × 6. Còn cặp cạnh gần nhau hơn.", 12: "12 là diện tích. Lưới rào đo bằng chu vi.", 26: "26 m là chu vi chuồng 1 × 12, dài nhất." } }),
  ],
  "data-1": [
    num("Hà ghi số trứng gà nhặt được trong 5 ngày: 4, 6, 5, 3, 6. Tổng cộng bao nhiêu quả?", 24,
      ["Con cộng theo thứ tự nào thì dễ nhất?", "4 + 6 = 10; 5 + 3 = 8", "Ghép các số thành tròn chục, rồi cộng phần còn lại."],
      "4 + 6 + 5 + 3 + 6 = 24 quả.", TAG,
      { wrong: { 18: "Con đã bỏ sót một ngày. Bảng có 5 ngày.", 6: "6 là số lớn nhất trong bảng, không phải tổng." } }),
    pick("Hỏi 8 bạn trong tổ, có 5 bạn thích bóng đá. Lan nói: “Cả trường đều thích bóng đá nhất.” Con thấy câu đó thế nào?", "Chưa đủ bằng chứng", ["Đúng, vì 5 nhiều hơn một nửa", "Chưa đủ bằng chứng", "Sai, vì không ai thích bóng đá"],
      ["Các bạn được hỏi là ai, có phải cả trường không?", "Dữ liệu chỉ nói về 8 bạn trong tổ.", "So nhóm được hỏi với nhóm mà Lan nói tới."],
      "Mới hỏi 8 bạn trong một tổ, nên chỉ biết về 8 bạn ấy, chưa nói được về cả trường.", TAG,
      { wrong: { "Đúng, vì 5 nhiều hơn một nửa": "5 trên 8 là của một tổ thôi. Các lớp khác có thể thích môn khác.", "Sai, vì không ai thích bóng đá": "Dữ liệu cho thấy có 5 bạn thích bóng đá, nên không thể nói không ai thích." } }),
  ],
  "data-2": [
    num("Quán có 3 loại bánh mì và 4 loại nước. Mỗi bạn chọn 1 bánh mì và 1 nước. Có bao nhiêu cách chọn?", 12,
      ["Nếu đã chọn bánh mì thứ nhất, có mấy cách chọn nước?", "Bánh thứ nhất: 4 cách; bánh thứ hai: 4 cách; …", "Mỗi loại bánh đi với cả 4 loại nước; có 3 loại bánh."],
      "3 × 4 = 12 cách chọn.", TAG,
      { wrong: { 7: "Con cộng 3 + 4. Mỗi loại bánh đi được với cả 4 loại nước.", 4: "Con mới tính cho một loại bánh." } }),
    num("Bé có 3 chiếc mũ và 2 đôi dép. Mỗi ngày bé chọn 1 mũ và 1 đôi dép. Bé đi được bao nhiêu ngày mà không lặp lại cách chọn?", 6,
      ["Với chiếc mũ thứ nhất, bé có mấy cách chọn dép?", "Mũ 1: 2 cách; mũ 2: 2 cách; mũ 3: 2 cách", "Mỗi chiếc mũ ghép với cả 2 đôi dép."],
      "3 × 2 = 6 cách chọn khác nhau, nên đi được 6 ngày.", TAG,
      { wrong: { 5: "Con cộng 3 + 2. Mỗi chiếc mũ ghép được với cả 2 đôi dép.", 3: "Con mới đếm số mũ. Mỗi mũ có 2 cách chọn dép." } }),
  ],
  "data-3": [
    pick("Hộp bút có 5 bút đỏ và 2 bút xanh. Nhắm mắt lấy 1 chiếc. Câu nào đúng?", "Dễ lấy được bút đỏ hơn", ["Dễ lấy được bút đỏ hơn", "Dễ lấy được bút xanh hơn", "Chắc chắn lấy được bút đỏ"],
      ["Màu nào có nhiều bút hơn trong hộp?", "Đỏ: 5 chiếc; xanh: 2 chiếc", "Màu nhiều hơn thì dễ lấy hơn, nhưng có chắc chắn không?"],
      "Có 5 bút đỏ, nhiều hơn 2 bút xanh, nên dễ lấy bút đỏ hơn. Nhưng vẫn có thể lấy được bút xanh.", TAG,
      { wrong: { "Dễ lấy được bút xanh hơn": "Bút xanh chỉ có 2 chiếc, ít hơn bút đỏ.", "Chắc chắn lấy được bút đỏ": "Trong hộp vẫn còn 2 bút xanh, nên có thể lấy được bút xanh." } }),
    pick("Bố đề nghị tung xúc xắc: ra 1 hoặc 2 thì Nam đi trước, ra 3, 4, 5 hoặc 6 thì Hà đi trước. Cách này có công bằng không?", "Không công bằng", ["Công bằng", "Không công bằng"],
      ["Mỗi bạn có mấy mặt xúc xắc giúp mình được đi trước?", "Nam: 2 mặt; Hà: 4 mặt", "So số mặt của hai bạn."],
      "Nam có 2 mặt, Hà có 4 mặt. Hà dễ được đi trước hơn nên cách này chưa công bằng.", TAG,
      { wrong: { "Công bằng": "Đếm lại: Nam chỉ có mặt 1 và mặt 2, còn Hà có tới 4 mặt." } }),
  ],
  "data-4": [
    num("Trên biểu đồ, cột của An ghi 32 cuốn sách, cột của Bình ghi 35 cuốn. Trục dọc bắt đầu từ 30 nên cột Bình trông cao hơn rất nhiều. Bình đọc nhiều hơn An bao nhiêu cuốn?", 3,
      ["Con nên tin chiều cao cột hay con số ghi trên cột?", "35 − 32", "Lấy số cuốn của Bình trừ số cuốn của An."],
      "35 − 32 = 3 cuốn. Cột trông chênh nhiều chỉ vì trục dọc bắt đầu từ 30.", TAG,
      { wrong: { 67: "Con đã cộng hai số. Câu hỏi là Bình đọc nhiều hơn bao nhiêu.", 5: "5 là chiều cao cột Bình trên hình (35 − 30), không phải chênh lệch thật." } }),
    pick("Một biểu đồ cột không ghi số trên trục. Bạn Tí nói: “Cột A cao gấp đôi cột B, nên A gấp đôi B.” Con có tin ngay không?", "Chưa tin, cần xem trục bắt đầu từ đâu", ["Tin, vì nhìn thấy rõ", "Chưa tin, cần xem trục bắt đầu từ đâu"],
      ["Nếu trục không bắt đầu từ 0 thì chiều cao cột có còn đúng không?", "Trục bắt đầu từ 20: cột 24 trông cao gấp đôi cột 22.", "Muốn so đúng, cần biết con số và vạch 0 của trục."],
      "Không thấy số và vạch 0 thì chưa biết A có thật gấp đôi B. Ví dụ trục bắt đầu từ 20 thì cột 24 trông cao gấp đôi cột 22.", TAG,
      { wrong: { "Tin, vì nhìn thấy rõ": "Chiều cao nhìn thấy có thể đánh lừa khi trục không bắt đầu từ 0." } }),
  ],
  "data-5": [
    pick("Bin gieo xúc xắc 12 lần mà chưa lần nào ra mặt 6. Bin nói xúc xắc này không thể ra mặt 6. Con thấy sao?", "Chưa thể kết luận", ["Bin nói đúng", "Chưa thể kết luận"],
      ["12 lần gieo đã đủ nhiều để chắc chắn chưa?", "Xúc xắc vẫn có mặt 6; có lúc may rủi làm nó lâu chưa ra.", "Cần gieo nhiều lần hơn nữa rồi mới so sánh."],
      "Mặt 6 vẫn có trên xúc xắc. Với ít lần gieo, kết quả có thể lệch do may rủi.", TAG,
      { wrong: { "Bin nói đúng": "Mặt 6 vẫn nằm trên xúc xắc. 12 lần chưa ra có thể chỉ do may rủi." } }),
    num("Bé quay vòng quay 20 lần và ghi lại: đỏ 9 lần, xanh 7 lần, còn lại là vàng. Vàng ra mấy lần?", 4,
      ["Đỏ và xanh ra tổng cộng bao nhiêu lần?", "9 + 7 = □; rồi 20 − □", "Cộng số lần đỏ và xanh, rồi lấy 20 trừ đi."],
      "Đỏ và xanh: 9 + 7 = 16 lần. Vàng: 20 − 16 = 4 lần.", TAG,
      { steps: 2, wrong: { 16: "16 là số lần ra đỏ và xanh. Con tìm phần còn lại.", 11: "Con mới trừ số lần ra đỏ. Còn số lần ra xanh nữa." } }),
  ],
  "data-6": [
    num("Cô hỏi 24 bạn về môn học yêu thích: 9 bạn chọn Toán, 8 bạn chọn Vẽ, còn lại chọn Âm nhạc. Có bao nhiêu bạn chọn Âm nhạc?", 7,
      ["Đã biết bao nhiêu bạn chọn Toán và Vẽ?", "9 + 8 = □; rồi 24 − □", "Cộng hai nhóm đã biết, rồi lấy tổng số bạn trừ đi."],
      "Toán và Vẽ: 9 + 8 = 17 bạn. Âm nhạc: 24 − 17 = 7 bạn.", TAG,
      { steps: 2, wrong: { 17: "17 là số bạn chọn Toán và Vẽ.", 15: "Con mới trừ số bạn chọn Toán. Còn các bạn chọn Vẽ nữa." } }),
    pick("Lớp muốn biết các bạn thích đi tham quan ở đâu. Câu hỏi nào công bằng nhất?", "Bạn muốn đi tham quan ở đâu nhất?", ["Bạn muốn đi tham quan ở đâu nhất?", "Đi sở thú vui nhất, bạn đồng ý không?", "Bạn không thích bảo tàng chán ngắt, đúng không?"],
      ["Câu hỏi nào không gợi ý sẵn câu trả lời?", "Câu dẫn dắt thường khen hoặc chê sẵn một nơi.", "Loại những câu đã khen hoặc chê một nơi."],
      "Câu hỏi để mỗi bạn tự nói nơi mình thích, không khen hay chê nơi nào trước.", TAG,
      { wrong: { "Đi sở thú vui nhất, bạn đồng ý không?": "Câu này khen sở thú trước, dễ làm bạn trả lời theo.", "Bạn không thích bảo tàng chán ngắt, đúng không?": "Câu này chê bảo tàng trước, dẫn dắt người trả lời." } }),
  ],
  "word-1": [
    num("Mẹ đi chợ, mua cá hết 45 nghìn, mua rau hết 18 nghìn, còn lại 37 nghìn. Lúc đầu mẹ mang bao nhiêu nghìn đồng?", 100,
      ["Đi ngược lại: mẹ đã tiêu hết bao nhiêu tiền?", "□ − 45 − 18 = 37", "Cộng tiền còn lại với hai khoản đã tiêu."],
      "37 + 18 + 45 = 100 nghìn đồng. Kiểm tra: 100 − 45 − 18 = 37.", TAG,
      { steps: 2, wrong: { 63: "63 nghìn là số tiền đã tiêu. Con cộng thêm số tiền còn lại.", 82: "Con quên cộng tiền rau." } }),
    num("Bà có một giỏ táo. Bà biếu hàng xóm một nửa, rồi cho cháu 4 quả, còn lại 8 quả. Lúc đầu giỏ có bao nhiêu quả?", 24,
      ["Việc cuối cùng bà làm là gì?", "Trước khi cho cháu: 8 + 4; trước khi biếu: gấp đôi", "Tháo từ cuối: cộng lại 4 quả, rồi nhân 2."],
      "Trước khi cho cháu: 8 + 4 = 12 quả. Đó là một nửa giỏ, nên lúc đầu có 12 × 2 = 24 quả.", TAG,
      { steps: 2, wrong: { 20: "Con nhân 2 trước rồi mới cộng 4. Phải tháo việc cuối cùng (cho cháu) trước.", 12: "12 quả mới là một nửa giỏ." } }),
  ],
  "word-2": [
    num("Nhà Mai mua 9 vé xem xiếc gồm vé trẻ em giá 20 nghìn và vé người lớn giá 40 nghìn, hết 260 nghìn đồng. Có bao nhiêu vé người lớn?", 4,
      ["Nếu cả 9 vé đều là vé trẻ em thì hết bao nhiêu tiền?", "9 × 20 = 180; còn thiếu 260 − 180", "Mỗi lần đổi một vé trẻ em thành vé người lớn thì thêm 20 nghìn: chia số tiền còn thiếu cho 20."],
      "Giả sử toàn vé trẻ em: 180 nghìn, thiếu 80 nghìn. Mỗi vé người lớn đắt hơn 20 nghìn: 80 : 20 = 4 vé người lớn.", TAG,
      { steps: 3, wrong: { 80: "80 nghìn là số tiền còn thiếu, không phải số vé.", 5: "5 là số vé trẻ em. Câu hỏi là số vé người lớn." } }),
    num("Ống heo của Nam có 12 tờ tiền gồm tờ 2 nghìn và tờ 5 nghìn, tổng cộng 39 nghìn đồng. Có bao nhiêu tờ 5 nghìn?", 5,
      ["Nếu cả 12 tờ đều là tờ 2 nghìn thì được bao nhiêu tiền?", "12 × 2 = 24; còn thiếu 39 − 24", "Mỗi lần đổi một tờ 2 nghìn thành tờ 5 nghìn thì thêm 3 nghìn: chia số còn thiếu cho 3."],
      "Giả sử toàn tờ 2 nghìn: 24 nghìn, thiếu 15 nghìn. Mỗi tờ 5 nghìn thêm 3 nghìn: 15 : 3 = 5 tờ 5 nghìn.", TAG,
      { steps: 3, wrong: { 15: "15 nghìn là số tiền còn thiếu. Mỗi lần đổi chỉ thêm 3 nghìn.", 7: "7 là số tờ 2 nghìn. Câu hỏi là số tờ 5 nghìn." } }),
  ],
  "word-3": [
    num("Mẹ có 10 cái bánh, chia vào đĩa xanh và đĩa đỏ, mỗi đĩa ít nhất 1 cái. Có bao nhiêu cách chia?", 9,
      ["Đĩa xanh có ít nhất mấy cái, nhiều nhất mấy cái?", "Đĩa xanh: 1, 2, 3, …; đĩa đỏ nhận phần còn lại", "Đếm số giá trị có thể của đĩa xanh."],
      "Đĩa xanh có thể có 1, 2, … hoặc 9 cái, mỗi số cho một cách: 9 cách.", TAG,
      { steps: 2, wrong: { 5: "Hai đĩa khác màu, nên 3 cái đĩa xanh – 7 cái đĩa đỏ khác với 7 cái đĩa xanh – 3 cái đĩa đỏ.", 10: "Mỗi đĩa ít nhất 1 cái, nên đĩa xanh không thể có đủ 10 cái." } }),
    num("Lan mua đồ dùng hết đúng 30 nghìn đồng, chỉ gồm bút giá 5 nghìn và thước giá 2 nghìn, mỗi loại ít nhất 1 chiếc. Có bao nhiêu cách mua?", 2,
      ["Nếu mua 1 bút, 2 bút, 3 bút… thì tiền còn lại có mua vừa đủ thước không?", "1 bút: còn 25; 2 bút: còn 20; 3 bút: còn 15; …", "Với mỗi số bút, xem tiền còn lại có mua vừa hết bằng thước 2 nghìn không, và còn ít nhất 1 thước."],
      "2 bút và 10 thước, hoặc 4 bút và 5 thước: 2 cách. 6 bút thì không còn tiền mua thước.", TAG,
      { steps: 3, wrong: { 3: "6 bút hết đúng 30 nghìn nhưng không còn thước nào; mỗi loại phải có ít nhất 1 chiếc.", 1: "Con còn bỏ sót một cách. Thử cả trường hợp 4 bút." } }),
  ],
  "word-4": [
    num("Số nhà của Tâm lớn hơn 30 và nhỏ hơn 50. Hai chữ số của nó giống nhau. Nó là số chẵn. Số nhà của Tâm là bao nhiêu?", 44,
      ["Những số nào từ 31 đến 49 có hai chữ số giống nhau?", "Chỉ có 33 và 44.", "Dùng manh mối cuối để loại bớt một số."],
      "Hai chữ số giống nhau: 33 hoặc 44. Số chẵn nên là 44.", TAG,
      { steps: 2, wrong: { 33: "33 là số lẻ, không thỏa manh mối cuối.", 22: "22 nhỏ hơn 30, không thỏa manh mối đầu." } }),
    pick("Bố hẹn: “Tuần sau bố về, nhưng không về vào cuối tuần.” Con đã biết chắc bố về ngày nào chưa?", "Chưa, còn 5 ngày có thể", ["Chưa, còn 5 ngày có thể", "Rồi, bố về thứ Hai", "Chưa, còn 7 ngày có thể"],
      ["Những ngày nào trong tuần không phải cuối tuần?", "Từ thứ Hai đến thứ Sáu", "Đếm số ngày còn thỏa manh mối."],
      "Còn thứ Hai, thứ Ba, thứ Tư, thứ Năm, thứ Sáu: 5 khả năng. Cần thêm manh mối mới biết chắc.", TAG,
      { wrong: { "Rồi, bố về thứ Hai": "Manh mối chưa nói gì về thứ Hai. Bố cũng có thể về thứ Ba hay thứ Sáu.", "Chưa, còn 7 ngày có thể": "Đã loại thứ Bảy và Chủ nhật, nên không còn đủ 7 ngày." } }),
  ],
  "word-5": [
    num("Cô mua 10 món gồm bút chì giá 3 nghìn và vở giá 7 nghìn, hết 46 nghìn đồng. Cô mua bao nhiêu quyển vở?", 4,
      ["Thử 5 vở và 5 bút chì thì hết bao nhiêu tiền?", "5 vở và 5 bút: 35 + 15 = 50 nghìn, nhiều hơn 46", "Mỗi lần đổi 1 vở thành 1 bút chì, tổng tiền giảm 4 nghìn; sửa dần cho tới 46."],
      "Thử 5 vở: 50 nghìn, thừa 4 nghìn. Đổi 1 vở thành 1 bút chì thì giảm 4 nghìn: 4 vở và 6 bút chì hết 28 + 18 = 46 nghìn.", TAG,
      { steps: 3, wrong: { 6: "6 là số bút chì. Câu hỏi là số vở.", 5: "5 vở và 5 bút chì hết 50 nghìn, nhiều hơn 46 nghìn." } }),
    num("Anh Tú xếp 42 cái ghế thành 8 hàng, có hàng 6 ghế và hàng 4 ghế. Có bao nhiêu hàng 6 ghế?", 5,
      ["Nếu cả 8 hàng đều có 4 ghế thì có bao nhiêu ghế?", "8 × 4 = 32; còn thiếu 42 − 32", "Mỗi lần đổi một hàng 4 ghế thành hàng 6 ghế thì thêm 2 ghế: sửa dần cho tới 42."],
      "Toàn hàng 4 ghế: 32 ghế, thiếu 10. Mỗi hàng 6 ghế thêm 2 ghế: 10 : 2 = 5 hàng. Kiểm tra: 5 × 6 + 3 × 4 = 30 + 12 = 42.", TAG,
      { steps: 3, wrong: { 10: "10 là số ghế còn thiếu, chưa phải số hàng.", 3: "3 là số hàng 4 ghế. Câu hỏi là số hàng 6 ghế." } }),
  ],
  "word-6": [
    num("Bốn bạn An, Bình, Chi, Dũng gặp nhau. Mỗi hai bạn bắt tay nhau đúng một lần. Có tất cả bao nhiêu cái bắt tay?", 6,
      ["An bắt tay với mấy bạn?", "An: 3 cái; Bình (trừ An): 2 cái; …", "Liệt kê theo thứ tự: mỗi bạn chỉ bắt tay với những bạn đứng sau mình."],
      "3 + 2 + 1 = 6 cái bắt tay.", TAG,
      { steps: 2, wrong: { 12: "Con đã đếm hai lần: An bắt tay Bình cũng chính là Bình bắt tay An.", 4: "Con mới đếm mỗi bạn một cái. Hãy liệt kê từng cặp." } }),
    num("Bé có 3 viên bi giống nhau, chia vào hộp A và hộp B (hộp có thể để trống). Có bao nhiêu cách chia?", 4,
      ["Hộp A có thể chứa mấy viên?", "Hộp A: 0, 1, 2 hoặc 3 viên", "Mỗi số bi của hộp A cho đúng một cách; đếm các cách đó."],
      "Hộp A có 0, 1, 2 hoặc 3 viên, hộp B nhận phần còn lại: 4 cách.", TAG,
      { steps: 2, wrong: { 3: "Con quên trường hợp hộp A để trống.", 2: "Hộp A và hộp B khác nhau, nên 1 viên – 2 viên khác với 2 viên – 1 viên." } }),
  ],
};
